# Generated by Django 4.2.3 on 2023-12-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('age', models.CharField(max_length=120)),
                ('birth', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('tickettype', models.CharField(max_length=120)),
                ('quantity', models.CharField(max_length=120)),
                ('date', models.DateField()),
            ],
        ),
    ]
